resources:
- name: resource-app-code
  type: git
  source:
    uri: https://github.com/chingor13/demoapp
    branch: master

- name: candidate-image
  type: docker-image
  source:
    repository: avvo/demoapp
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}
    tag: candidate

- name: final-image
  type: docker-image
  source:
    repository: avvo/demoapp
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}
    tag: latest

jobs:
- name: build-candidate
  plan:
  - get: resource-app-code
    trigger: true

  - put: candidate-image
    params:
      build: resource-app-code

- name: verify-build
  plan:
  - get: candidate-image
    trigger: true
    passed: [build-candidate]

  - task: unit-tests
    file: resource-app-code/ci/unit-tests.yml

- name: deploy-stag
  plan:
  - get: candidate-image
    trigger: true
    passed: [verify-build]

  - task: acceptance-tests
    file: resource-app-code/ci/acceptance-tests.yml

  - put: final-image
    params:
      build: ./demoapp

- name: deploy-production
  plan:
  - get: final-image
    trigger: true
    passed: [deploy-stag]

  - task: deploy-production
    file: resource-app-code/ci/deploy-production.yml
