resources:
- name: demoapp
  type: git
  source:
    uri: https://github.com/chingor13/demoapp
    branch: master

- name: demoapp-image
  type: docker-image
  source:
    repository: avvo/demoapp

jobs:
- name: test-app
  plan:
  - get: demoapp
    trigger: true
  - task: tests
    file: demoapp/ci/build.yml
  - put: demoapp-image
    params:
      build: ./demoapp
