resources:
- name: master
  type: git
  source:
    uri: https://github.com/chingor13/demoapp
    branch: master

- name: candidate-image
  type: docker-image
  source:
    repository: "https://registry.docker.prod.avvo.com:443/avvo/demoapp"

- name: final-image
  type: docker-image
  source:
    repository: avvo/demoapp

jobs:
- name: build-candidate
  plan:
  - get: master
    trigger: true

  - put: candidate-image
    params:
      build: ./demoapp

  - task: unit-tests
    file: demoapp/ci/unit-tests.yml

- name: deploy-stag
  plan:
  - get: candidate-image
    trigger: true
    passed: [build-candidate]

  - task: acceptance-tests
    file: demoapp/ci/acceptance-tests.yml

  - put: final-image
    params:
      build: ./demoapp

- name: deploy-production
  plan:
  - get: final-image
    trigger: true
    passed: [deploy-stag]

  - task: deploy-production
    file: demoapp/ci/deploy-production.yml
